version: "3"

services:
  app:
    container_name: node
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    command: ["npm", "${NPM_CMD:-start}"]

  mongo:
    container_name: mongo
    image: mongo:bionic
    expose:
      - "27017"
    volumes:
      - "db:/data/db"

volumes:
  db:
